services:
  web:
    # "." significa que el Dockerfile está en esta misma carpeta
    build: . 
    container_name: incidencies-web
    ports:
      - "8080:80"
    volumes:
      # "./PROJECTE FINAL/PROJECTE" es la ruta a tus archivos PHP
      - "./PROJECTE FINAL/PROJECTE:/var/www/html"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: incidencies-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: incidencies
      MYSQL_USER: usuari
      MYSQL_PASSWORD: usuari1234
    volumes:
      - mysql-data:/var/lib/mysql
      # Actualizamos la ruta a tu nueva carpeta db_init
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: incidencies-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge